name: Build on Mac test

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - run: |
          echo $JAVA_HOME
          export CPPFLAGS="-I$JAVA_HOME/include"
          export CXXFLAGS="-I$JAVA_HOME/include"
          brew install zlib
          brew install bzip2 lz4 snappy
          ROCKSDB_DISABLE_JEMALLOC=1 PORTABLE=1 DEBUG_LEVEL=0 make -j 4 rocksdbjavastatic
